### ISSUE TITLE
关于检测部署的问题

### ISSUE THREAD

**Issue by Fly-Pluche** [fandesfyf/Ar_project#2]
请问你的Paddle模型是部署在云端的吗，把树莓派检测到的视频流通过socker传给模型，模型跑出结果再传给树莓派？

**Comment by fandesfyf** [comment]
是的，我们的项目其中一个买点就是利用5g的低延时，所以部署在云端是没有问题的；其实也可以部署在树莓派上利用好末端算力，不过好像之前paddle是不完全支持树莓派的，建议换成其他框架。。。

**Comment by Fly-Pluche** [comment]
可以问一下，你们违规车辆检测了一些什么违规行为，是通过什么进行检测的？

**Comment by fandesfyf** [comment]
> 可以问一下，你们违规车辆检测了一些什么违规行为，是通过什么进行检测的？

我们做了车辆压实线还有限号的自动识别和上报，就是通过深度学习通过自己标定的数据训练的模型来检测的啊，不然用paddle干嘛。

**Comment by Fly-Pluche** [comment]
百度的模型效果好吗，我听说换训练集后，效果差了很多

**Comment by fandesfyf** [comment]
> 百度的模型效果好吗，我听说换训练集后，效果差了很多

还可以啊，我们就自己标了几百张照片然后用了yolov3的预训练模型来训练。AIstudio的训练项目的链接放在最后，你可以去看一下。

**Comment by Fly-Pluche** [comment]
好的，谢谢
